# This is a basic workflow to help you get started with Actions

name: Building Kernel For Enterprise NVIDIA AGX

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Preparing build
        run: |
          sudo apt install -y build-essential bc
          wget https://developer.download.nvidia.com/embedded/L4T/r36_Release_v2.0/toolchain/aarch64--glibc--stable-2022.08-1.tar.bz2
          tar -xjf aarch64--glibc--stable-2022.08-1.tar.bz2
          ls -a
          mkdir kernel_out
      # Runs a set of commands using the runners shell
      - name: Start building
        run: |
          export CROSS_COMPILE_AARCH64_PATH=/home/runner/work/linux-nvidia/linux-nvidia/aarch64--glibc--stable-2022.08-1
          export CROSS_COMPILE_AARCH64=/home/runner/work/linux-nvidia/linux-nvidia/aarch64--glibc--stable-2022.08-1/bin/aarch64-buildroot-linux-gnu-
          ./nvbuild.sh -o $PWD/kernel_out